DESIGN_NAME := restoring-divider
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_restoring_divider
TOP_GUI := gui_restoring_divider
WAVE_GUI := $(wildcard sim/wave.do)
DEPS := ripple-carry-adder
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
