DESIGN_NAME := restoring-divider
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_restoring_divider
TOP_GUI := gui_restoring_divider
WAVE_GUI := $(realpath $(wildcard sim/wave.do))
DEPS := ripple-carry-adder
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
