DESIGN_NAME := booth-multiplier
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_booth_multiplier
TOP_GUI := gui_booth_multiplier
WAVE_GUI := $(wildcard sim/wave.do)
DEPS :=
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
