DESIGN_NAME := booth-multiplier
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_booth_multiplier
TOP_GUI := gui_booth_multiplier
WAVE_GUI := $(realpath $(wildcard sim/wave.do))
DEPS :=
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
