DESIGN_NAME := ripple-carry-adder
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_ripple_carry_adder
TOP_GUI := gui_ripple_carry_adder
WAVE_GUI := $(wildcard sim/wave.do)
DEPS := full-adder
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
