DESIGN_NAME := ripple-carry-adder
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_ripple_carry_adder
DEPS := full-adder
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
