DESIGN_NAME := ripple-carry-adder
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_ripple_carry_adder
TOP_GUI := gui_ripple_carry_adder
WAVE_GUI := $(realpath $(wildcard sim/wave.do))
DEPS := full-adder
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
