DESIGN_NAME := cpu-mips-pipelined-four-issue
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_cpu_mips_pipelined_four_issue
TOP_GUI :=
WAVE_GUI :=
DEPS :=
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
