DESIGN_NAME := shift-add-multiplier
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_shift_add_multiplier
TOP_GUI := gui_shift_add_multiplier
WAVE_GUI := $(wildcard sim/wave.do)
DEPS :=
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
