DESIGN_NAME := full-adder
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_full_adder
DEPS :=
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
