DESIGN_NAME := cpu-mips-single-cycle
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_isort_cpu_mips #tb_basic_cpu_mips
TOP_GUI :=
WAVE_GUI :=
DEPS :=
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
