DESIGN_NAME := cpu-mips-single-cycle
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_isort_cpu_mips #tb_basic_cpu_mips
TOP_GUI :=
WAVE_GUI :=
DEPS :=
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
