ifneq ($(strip $(FORCED_SIMULATOR)),)
    ifneq ($(HDL_SIMULATOR),$(FORCED_SIMULATOR))
        $(error Simulator has been forced for a module: $(FORCED_SIMULATOR))
    endif
endif

ifeq ($(HDL_SIMULATOR),modelsim)
    include $(PRJ_UTILITY)/Makefile.modelsim
else ifeq ($(HDL_SIMULATOR),xsim)
    include $(PRJ_UTILITY)/Makefile.xsim
else
    # Fallback or error handling
    $(error Unknown HDL_SIMULATOR: $(HDL_SIMULATOR))
endif

