DESIGN_NAME := array-multiplier
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_array_multiplier
DEPS := full-adder
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
