DESIGN_NAME := array-multiplier
HDL_FILES := $(realpath $(wildcard hdl/*.v))
TB_FILES := $(realpath $(wildcard sim/*.v))
TOP_TB := tb_array_multiplier
DEPS := full-adder
MODELSIM_COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
