DESIGN_NAME := cpu-mips-pipelined
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_cpu_mips_pipelined
TOP_GUI :=
WAVE_GUI :=
DEPS :=
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
