DESIGN_NAME := carry-look-ahead-adder
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB := tb_carry_look_ahead_adder
DEPS :=
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
