DESIGN_NAME := pwm-generator
HDL_FILES := $(wildcard hdl/*.v)
TB_FILES := $(wildcard sim/*.v)
TOP_TB :=
TOP_GUI := gui_pwm_generator
WAVE_GUI := $(wildcard sim/wave.do)
DEPS :=
COMPILE_OPTIONS :=

include $(PRJ_UTILITY)/Makefile.common
