DESIGN_NAME := pwm-generator
INC_FILES := $(wildcard inc/*.vh)
HDL_FILES := $(wildcard hdl/*.v) $(wildcard hdl/*.sv)
TB_FILES := $(wildcard sim/*.v)
TOP_TB :=
TOP_GUI := gui_pwm_generator
WAVE_GUI := $(wildcard sim/wave.do)
DEPS :=
COMPILE_OPTIONS := -sv

include $(PRJ_UTILITY)/Makefile.common
